In [1]:
import numpy as np

In [4]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
arr + 10

In [9]:
# 배열생성 : 리스트를 배열로 변환
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [10]:
#2차원 배열
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [13]:
# 임의의 데이터로 배열을 생성
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# 일련번호 생성 : 연속된 숫자 생성
seq1 = np.arange(1, 10, 2)
print(seq1)

[1 3 5 7 9]


In [19]:
# 범위안에 동일한 간격의 숫자 생성
linespace = np.linspace(0, 1, 5)
print(linespace)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
# 배열의 속성 확인
arr = np.array([[1,2,3], [4,5,6]])

In [60]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [29]:
# 인덱싱
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[-1])

10
40


In [30]:
arr = np.array([[1,2,3], [4,5,6]])

In [33]:
print(arr[0], type(arr[0]))


[1 2 3] <class 'numpy.ndarray'>


In [35]:
print(arr[0][1])
print(arr[-1][0])

2
4


In [42]:
# 슬라이싱
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[::2])

[20 30 40]
[10 20 30]
[10 30 50]


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(arr[:2,1:])
print(arr[1:, 1:3])

[[2 3]
 [5 6]]
[[5 6]
 [8 9]]


In [57]:
# 배열의 연산
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1+arr2)
print(arr1*arr2)
print(arr1**arr2)

[5 7 9]
[ 4 10 18]
[  1  32 729]


In [59]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr+10)

[[11 12 13]
 [14 15 16]]


In [63]:
# 구조 변경 : 2 -> 1 , 1 -> 2
arr = np.array([1,2,3,4,5,6])

reshape = arr.reshape(3,2)
print(reshape)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
flat_arr = arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [67]:
arr = np.array([1,2,3,4,5,6])

In [68]:
filter_arr = arr[arr > 3]
print(filter_arr)

[4 5 6]


In [69]:
# 랜덤 생성
ran_val = np.random.rand(3)
print(ran_val)

[0.72320507 0.84241366 0.89811799]


In [75]:
ran_int = np.random.randint(1, 10, size=(3,4))
print(ran_int)

[[9 8 5 2]
 [5 7 9 7]
 [9 2 8 5]]


In [77]:
import pandas as pd

In [78]:
# 데이터 프레임 생성 : 2차원 형식의 데이터 구조
data = {
    'name' : ['son', 'king', 'scott'],
    'age' : [30, 40, 50]
}

df = pd.DataFrame(data)

In [82]:
df.head(n=2)

name  age
0   son   30
1  king   40

In [84]:
df.tail(n=2)

name  age
1   king   40
2  scott   50

In [91]:
filter_df = df[df['age'] >= 40]
print(filter_df)

    name  age
1   king   40
2  scott   50


In [89]:
print(df['age'].sum())
print(df['age'].mean())

120
40.0


In [97]:
# Series : 1차원 구조, (값, index)
s1 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
print(s1, type(s1))

a    100
b    200
c    300
dtype: int64 <class 'pandas.core.series.Series'>


In [98]:
print(s1['b'])
print(s1.index)
print(s1.values)

200
Index(['a', 'b', 'c'], dtype='object')
[100 200 300]


In [99]:
# DataFrame : 2차원 구조 (표, 테이블)
data = {
    'name' : ['son', 'king', 'scott'],
    'age' : [30, 40, 50]
}

df = pd.DataFrame(data)

In [100]:
df

name  age
0    son   30
1   king   40
2  scott   50

In [101]:
# 데이터의 사이즈
print(df.shape)

(3, 2)


In [102]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None


In [104]:
print(df.describe())

        age
count   3.0
mean   40.0
std    10.0
min    30.0
25%    35.0
50%    40.0
75%    45.0
max    50.0


In [105]:
print(df['name'])

0      son
1     king
2    scott
Name: name, dtype: object


In [106]:
print(df[['name', 'age']])

    name  age
0    son   30
1   king   40
2  scott   50


In [164]:
# DataFrame : 2차원 구조 (표, 테이블)
data = {
    'name' : ['son', 'king', 'scott'],
    'age' : [30, 40, 25],
    'score' : [90, 85, 95],
}

df = pd.DataFrame(data)

In [110]:
chk_score = df[df['score'] >= 90]
print(chk_score)

    name  age  score
0    son   30     90
2  scott   50     95


In [165]:
# 열 추가
df['passed'] = df['score'] >= 90
df

name  age  score  passed
0    son   30     90    True
1   king   40     85   False
2  scott   25     95    True

In [166]:
# 행 추가 : pd.append()
new_row = {
    'name' : ['smith'],
    'age' : [24],
    'score' : [88],
    'passed' : [False]
}

df2 = pd.DataFrame(new_row)
df = pd.concat([df, df2], ignore_index=True)
df

name  age  score  passed
0    son   30     90    True
1   king   40     85   False
2  scott   25     95    True
3  smith   24     88   False

In [133]:
df.loc[0, 'score'] = 100
df

name  age  score  passed
0    son   30    100    True
1   king   40     85   False
2  scott   25     95    True

In [134]:
df['passed'] = df['score'] >= 80
df

name  age  score  passed
0    son   30    100    True
1   king   40     85    True
2  scott   25     95    True

In [144]:
df.loc[1, 'score'] = None
df

name  age  score  passed
0    son   30  100.0    True
1   king   40    NaN    True
2  scott   25   95.0    True

In [143]:
print(df.isnull())

    name    age  score  passed
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False


In [141]:
df['score'] = df['score'].fillna(0)
df

name  age  score  passed
0    son   30  100.0    True
1   king   40    0.0    True
2  scott   25   95.0    True

In [145]:
df = df.dropna()
df

name  age  score  passed
0    son   30  100.0    True
2  scott   25   95.0    True

In [149]:
sorted_df = df.sort_values(by='score', ascending=False)
print(sorted_df)

    name  age  score
2  scott   25     95
0    son   30     90
1   king   40     85


In [168]:
# 그룹핑 : ~별
data = {
    'team' : ['A', 'A', 'B', 'B', 'C'],
    'score' : [85, 90, 78, 88, 70]
}

df = pd.DataFrame(data)
df

team  score
0    A     85
1    A     90
2    B     78
3    B     88
4    C     70

In [169]:
data2 = {
    'team' : ['C'],
    'score' : [100]
}

df2 = pd.DataFrame(data2)
df = pd.concat([df, df2], ignore_index=True)
df

team  score
0    A     85
1    A     90
2    B     78
3    B     88
4    C     70
5    C    100

In [158]:
group_data = df.groupby('team')['score'].mean()
print(group_data)

team
A    87.5
B    83.0
C    70.0
Name: score, dtype: float64


In [161]:
# CSV 저장
df.to_csv('output.csv', index=False)

group_data.to_csv('result.csv')

In [1]:
import requests

In [3]:
url= 'https://jsonplaceholder.typicode.com/posts'
response = requests.get(url)

In [10]:
if response.status_code == 200:
    print('응답 성공')
    print(response.text[:300])
else:
    print(f'오류발생 : {response.status_code}')

응답 성공
[
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architect


In [8]:
data_obj = response.json()

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic c

In [9]:
type(data_obj)

list

In [11]:
for post in data_obj:
    print('title : ','title', post)

title {'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
title {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}
title {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}
title {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rer

In [3]:
from bs4 import BeautifulSoup

In [19]:
html_doc = """
 <html>
    <head>
        <title>Example Page</title>
    </head>
    <body>
        <h1>Welcome to Web Scraping</h1>
        <p class="description">This is an example paragraph.</p>
        <a href="https://example.com1">Visit Example1</a>
        <a href="https://example.com2">Visit Example2</a>
        <a href="https://example.com3">Visit Example3</a>
        <a href="https://example.com4">Visit Example4</a>
    </body>
 </html>
 """

In [20]:
# Beautifulsoup 객체 생성
soup = BeautifulSoup(html_doc, 'html.parser')
print(soup.title.string)
print(soup.h1.string)
print(soup.p.string)
print(soup.p['class'])

Example Page
Welcome to Web Scraping
This is an example paragraph.
['description']


In [21]:
# find, find_all
a_tag = soup.find('a')
print(a_tag)

<a href="https://example.com1">Visit Example1</a>


In [25]:
a_tags = soup.find_all('a')
print(a_tags)
links = []
for a_tag in a_tags :
    #print(a_tag['href'])
    links.append(a_tag['href'])

print(links)

[<a href="https://example.com1">Visit Example1</a>, <a href="https://example.com2">Visit Example2</a>, <a href="https://example.com3">Visit Example3</a>, <a href="https://example.com4">Visit Example4</a>]
['https://example.com1', 'https://example.com2', 'https://example.com3', 'https://example.com4']


In [27]:
import csv

data = [
    ['Name', 'Age', 'City'],
    ['Alice', 30, 'New York'],
    ['Bob', 25, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
 ]

In [29]:
with open('data1.csv', 'w', encoding='utf8', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

print('save ok!')

save ok!


In [31]:
import pandas as pd
data = pd.read_csv('data1.csv')
print(data)

      Name  Age         City
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago


In [2]:
# 데이터 준비
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [30, 25, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
 }

df = pd.DataFrame(data)

In [3]:
# 엑셀 저장
df.to_excel('data1.xlsx', index=False)
print('save ok!')

save ok!


In [4]:
data2 = pd.read_excel('data1.xlsx')
print(data2)

      Name  Age         City
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago


In [5]:
import json
# 데이터 준비
data = {
 'people': [
        {'name': 'Alice', 'age': 30, 'city': 'New York'},
        {'name': 'Bob', 'age': 25, 'city': 'Los Angeles'},
        {'name': 'Charlie', 'age': 35, 'city': 'Chicago'}
    ]
 }

In [6]:
with open('data1.json', 'w', encoding='utf-8') as file :
    json.dump(data, file, indent=4)

print("save ok!")

save ok!


In [8]:
with open('data1.json', mode='r') as file :
    data3 = json.load(file)

print(type(data3), data3)

<class 'dict'> {'people': [{'name': 'Alice', 'age': 30, 'city': 'New York'}, {'name': 'Bob', 'age': 25, 'city': 'Los Angeles'}, {'name': 'Charlie', 'age': 35, 'city': 'Chicago'}]}
